### ISSUE TITLE
issue related DIM

### ISSUE THREAD

**Issue by ccmeth** [raphaelmourad/TADreg#3]
Hi,

Thanks a lot for providing such a powerful tool for us to identify diff-tad boundaries. I used DIM function twice today. At the first time, it run without any issue, however, when I applied this function to another two samples, an error occured:

"error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': Cholmod error 'problem too large'"

Could you please help me to address such issue?
Thanks,
Hao

**Comment by ccmeth** [comment]
Possibly due to the sparseness? Samples without issue and with issue are 50-kb and 25-kb resolution, respectively.

**Comment by raphaelmourad** [comment]
Hi,
Cholmod error 'problem too large'" means you don't have enough RAM on your computer to run DIM with the resolution 25kb. At 50kb, it works since the Hi-C matrix is not too big, but at 25kb, the Hi-C matrix becomes too big for your computer RAM.

**Comment by ccmeth** [comment]
> Hi, Cholmod error 'problem too large'" means you don't have enough RAM on your computer to run DIM with the resolution 25kb. At 50kb, it works since the Hi-C matrix is not too big, but at 25kb, the Hi-C matrix becomes too big for your computer RAM.

Thanks for your timely reply, yeah, 50kb resolution again worked.
